kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30000   # NodePort in service.yaml
        hostPort: 30000        # Port on your Mac's localhost
        protocol: TCP
